server {
    listen 80;
    server_name app3.academia.ar;

    root /var/www/smart-hive/dist;
    index index.html;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Assets estáticos con cache
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA: redirigir todo al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
