/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedPrediccionesRouteImport } from './routes/_protected.predicciones'
import { Route as ProtectedNotificacionesRouteImport } from './routes/_protected.notificaciones'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedConfiguracionRouteImport } from './routes/_protected.configuracion'
import { Route as ProtectedColmenaresRouteImport } from './routes/_protected.colmenares'
import { Route as ProtectedAnalisisRouteImport } from './routes/_protected.analisis'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPrediccionesRoute = ProtectedPrediccionesRouteImport.update({
  id: '/predicciones',
  path: '/predicciones',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNotificacionesRoute = ProtectedNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedConfiguracionRoute = ProtectedConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedColmenaresRoute = ProtectedColmenaresRouteImport.update({
  id: '/colmenares',
  path: '/colmenares',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnalisisRoute = ProtectedAnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analisis': typeof ProtectedAnalisisRoute
  '/colmenares': typeof ProtectedColmenaresRoute
  '/configuracion': typeof ProtectedConfiguracionRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/notificaciones': typeof ProtectedNotificacionesRoute
  '/predicciones': typeof ProtectedPrediccionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analisis': typeof ProtectedAnalisisRoute
  '/colmenares': typeof ProtectedColmenaresRoute
  '/configuracion': typeof ProtectedConfiguracionRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/notificaciones': typeof ProtectedNotificacionesRoute
  '/predicciones': typeof ProtectedPrediccionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/analisis': typeof ProtectedAnalisisRoute
  '/_protected/colmenares': typeof ProtectedColmenaresRoute
  '/_protected/configuracion': typeof ProtectedConfiguracionRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/notificaciones': typeof ProtectedNotificacionesRoute
  '/_protected/predicciones': typeof ProtectedPrediccionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analisis'
    | '/colmenares'
    | '/configuracion'
    | '/dashboard'
    | '/notificaciones'
    | '/predicciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analisis'
    | '/colmenares'
    | '/configuracion'
    | '/dashboard'
    | '/notificaciones'
    | '/predicciones'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/analisis'
    | '/_protected/colmenares'
    | '/_protected/configuracion'
    | '/_protected/dashboard'
    | '/_protected/notificaciones'
    | '/_protected/predicciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/predicciones': {
      id: '/_protected/predicciones'
      path: '/predicciones'
      fullPath: '/predicciones'
      preLoaderRoute: typeof ProtectedPrediccionesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/notificaciones': {
      id: '/_protected/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof ProtectedNotificacionesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/configuracion': {
      id: '/_protected/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ProtectedConfiguracionRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/colmenares': {
      id: '/_protected/colmenares'
      path: '/colmenares'
      fullPath: '/colmenares'
      preLoaderRoute: typeof ProtectedColmenaresRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analisis': {
      id: '/_protected/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof ProtectedAnalisisRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAnalisisRoute: typeof ProtectedAnalisisRoute
  ProtectedColmenaresRoute: typeof ProtectedColmenaresRoute
  ProtectedConfiguracionRoute: typeof ProtectedConfiguracionRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedNotificacionesRoute: typeof ProtectedNotificacionesRoute
  ProtectedPrediccionesRoute: typeof ProtectedPrediccionesRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAnalisisRoute: ProtectedAnalisisRoute,
  ProtectedColmenaresRoute: ProtectedColmenaresRoute,
  ProtectedConfiguracionRoute: ProtectedConfiguracionRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedNotificacionesRoute: ProtectedNotificacionesRoute,
  ProtectedPrediccionesRoute: ProtectedPrediccionesRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
